## Setup Spark and SQL Contexts

In [1]:
from pyspark import SparkContext
from pyspark import SparkConf
from pyspark.sql import SQLContext

sparkContext = SparkContext.getOrCreate()
sqlContext = SQLContext(sparkContext)

sqlContext

In [2]:
sys.path

['/root/spark-1.6.1-bin-fluxcapacitor/python/lib/py4j-0.9-src.zip',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.fasterxml.jackson.core_jackson-core-2.6.6.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/commons-codec_commons-codec-1.9.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.apache.httpcomponents_httpcore-4.4.4.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.fasterxml.jackson.dataformat_jackson-dataformat-cbor-2.6.6.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.fasterxml.jackson.core_jackson-databind-2.6.6.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/software.amazon.ion_ion-java-1.0.0.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.apache.httpcomponents_httpclient-4.5.2.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/commons-logging_commons-logging-1.1.3.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_jmespath-java-1.0.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-swf-libraries-1.11.22.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-models-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-core-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-snowball-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-applicationautoscaling-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-discovery-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-cognitoidp-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-marketplacemeteringservice-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-dms-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-gamelift-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-acm-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-api-gateway-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-iot-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-inspector-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-marketplacecommerceanalytics-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-waf-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-elasticsearch-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-devicefarm-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-codecommit-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-efs-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-directory-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-machinelearning-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-workspaces-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-ssm-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-cloudhsm-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-ecr-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-ecs-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-lambda-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-config-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-kms-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-codepipeline-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-codedeploy-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-cloudwatchmetrics-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-cloudsearch-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-autoscaling-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-ses-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-opsworks-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-kinesis-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-cloudfront-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-cloudformation-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-directconnect-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-cognitosync-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-cognitoidentity-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-events-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-logs-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-cloudwatch-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-cloudtrail-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-sns-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-dynamodb-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-ec2-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-elastictranscoder-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-elasticache-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-emr-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-elasticloadbalancingv2-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-elasticloadbalancing-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-datapipeline-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-iam-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-glacier-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-elasticbeanstalk-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-redshift-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-rds-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-sqs-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-sts-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-importexport-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-s3-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-route53-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-storagegateway-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-simpleworkflow-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-servicecatalog-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-simpledb-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.amazonaws_aws-java-sdk-support-1.11.39.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/javax.xml.bind_jaxb-api-2.2.7.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/xalan_xalan-2.7.0.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/xerces_xercesImpl-2.8.0.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/xml-apis_xml-apis-1.3.03.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/javax.json_javax.json-api-1.0.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.googlecode.efficient-java-matrix-library_ejml-0.23.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/de.jollyday_jollyday-0.4.7.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/joda-time_joda-time-2.9.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.io7m.xom_xom-1.2.10.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.wordnik_swagger-annotations-1.5.3-M1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.apache.nifi_nifi-client-dto-0.6.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.apache.nifi_nifi-utils-0.6.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.apache.nifi_nifi-api-0.6.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.sun.jersey_jersey-server-1.2.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.apache.nifi_nifi-site-to-site-client-0.6.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.univocity_univocity-parsers-1.5.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.apache.commons_commons-csv-1.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.tukaani_xz-1.0.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.apache.commons_commons-compress-1.4.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.xerial.snappy_snappy-java-1.0.5.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.codehaus.jackson_jackson-mapper-asl-1.9.13.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.codehaus.jackson_jackson-core-asl-1.9.13.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.apache.avro_avro-1.7.6.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.scalamacros_quasiquotes_2.10-2.0.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.googlecode.javaewah_JavaEWAH-0.6.6.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.codahale.metrics_metrics-core-3.0.2.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/io.netty_netty-3.9.0.Final.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.scala-lang_scala-reflect-2.10.5.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.twitter_jsr166e-1.1.0.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.joda_joda-convert-1.2.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.datastax.cassandra_cassandra-driver-core-2.1.5.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.apache.cassandra_cassandra-clientutil-2.1.5.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.spark-project.spark_unused-1.0.0.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.ankurdave_part_2.10-0.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.thoughtworks.paranamer_paranamer-2.8.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.json4s_json4s-scalap_2.10-3.3.0.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.json4s_json4s-ast_2.10-3.3.0.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.json4s_json4s-core_2.10-3.3.0.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.apache.commons_commons-pool2-2.4.2.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/stax_stax-api-1.0.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.codehaus.jettison_jettison-1.2.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/xpp3_xpp3_min-1.1.4c.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/xmlpull_xmlpull-1.1.3.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.sun.jersey.contribs_jersey-apache-client4-1.8.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.thoughtworks.xstream_xstream-1.4.2.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.sun.jersey_jersey-bundle-1.9.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/javax.ws.rs_jsr311-api-1.1.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.google.code.findbugs_annotations-2.0.0.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.google.guava_guava-14.0.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/commons-lang_commons-lang-2.6.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/commons-configuration_commons-configuration-1.8.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/asm_asm-3.1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/org.sonatype.sisu.inject_cglib-2.2.1-v20090111.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/aopalliance_aopalliance-1.0.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/javax.inject_javax.inject-1.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.netflix.eureka_eureka-client-1.1.110.jar',
 u'/tmp/spark-f41702cc-5fbe-4ed8-ada4-1a0e12531869/userFiles-82126adc-a6a3-4318-8afc-04c425c2cecf/com.netflix.servo_servo-core-0.5.5.jar',

In [3]:
!export

export AIRFLOW_HOME='/root/airflow'
export AKKA_VERSION='2.3.11'
export ALGEBIRD_VERSION='0.11.0'
export ANKUR_PART_VERSION='0.1'
export ATLAS_HOME='/root/atlas-1.4.5'
export ATLAS_VERSION='1.4.5'
export BAZEL_HOME='/root/bazel-0.3.0'
export BAZEL_VERSION='0.3.0'
export BETTER_FILES_VERSION='2.14.0'
export CASSANDRA_HOME='/root/apache-cassandra-2.2.6'
export CASSANDRA_VERSION='2.2.6'
export CLICOLOR='1'
export CODAHALE_METRICS_VERSION='3.1.2'
export COMMONS_DAEMON_VERSION='1.0.15'
export CONFIG_HOME='/root/pipeline/config'
export CONFLUENT_HOME='/root/confluent-3.0.0'
export CONFLUENT_VERSION='3.0.0'
export DATASETS_HOME='/root/pipeline/datasets'
export DEV_INSTALL_HOME='/root'
export DYNOMITE_HOME='/root/dynomite'
export DYNO_VERSION='1.4.6'
export ELASTICSEARCH_HOME='/root/elasticsearch-2.3.0'
export ELASTICSEARCH_VERSION='2.3.0'
export FINAGLE_VERSION='6.34.0'
export FLINK_HOME='/root/flink-1.0.0'
export FLINK_VERSION='1.0.0'
export GENSORT_VERSION='1.5'
export GIT_PAGER='cat'
export GRAPHFRAMES_VERSION='0.1.0-spark1.6'
export GUAVA_VERSION='14.0.1'
export HADOOP_HOME='/root/hadoop-2.6.0'
export HADOOP_USER_CLASSPATH_FIRST='true'
export HADOOP_VERSION='2.6.0'
export HIVE_HOME='/root/apache-hive-1.2.1-bin'
export HIVE_VERSION='1.2.1'
export HOME='/root'
export HOSTNAME='pipeline-master-v5-ytpc'
export HTML_HOME='/root/pipeline/myapps/html'
export HYSTRIX_DASHBOARD_HOME='/root/hystrix-dashboard-1.5.3'
export HYSTRIX_DASHBOARD_VERSION='1.5.3'
export HYSTRIX_VERSION='1.5.3'
export INDEXEDRDD_VERSION='0.3'
export JANINO_VERSION='2.7.8'
export JAVA_HOME='/usr/lib/jvm/java-8-oracle'
export JAVA_OPTS='-Xmx10G -XX:+CMSClassUnloadingEnabled'
export JBLAS_VERSION='1.2.4'
export JEDIS_VERSION='2.7.3'
export JMETER_HOME='/root/apache-jmeter-3.0'
export JMETER_VERSION='3.0'
export JPMML_SPARKML_VERSION='1.0.4'
export JPY_PARENT_PID='28368'
export JSON4S_VERSION='3.3.0'
export KAFKA_CLIENT_VERSION='0.10.0.0'
export KIBANA_HOME='/root/kibana-4.5.0-linux-x64'
export KIBANA_VERSION='4.5.0'
export LESSCLOSE='/usr/bin/lesspipe %s %s'
export LESSOPEN='| /usr/bin/lesspipe %s'
export LOGSTASH_HOME='/root/logstash-2.3.0'
export LOGSTASH_VERSION='2.3.0'
export LOGS_HOME='/root/pipeline/logs'
export LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:'
export MAXMIND_GEOIP_VERSION='2.5.0'
export MPLBACKEND='module://ipykernel.pylab.backend_inline'
export MYAPPS_HOME='/root/pipeline/myapps'
export MYSQL_CONNECTOR_JAR='/usr/share/java/mysql-connector-java.jar'
export NIFI_HOME='/root/nifi-0.6.1'
export NIFI_VERSION='0.6.1'
export OLDPWD='/root/pipeline/config/bash'
export PAGER='cat'
export PATH='/usr/local/bin:/root/pipeline/myapps/serving:/root/pipeline/myapps/serving/prediction:/root/dynomite:/root/apache-jmeter-3.0/bin:/root/titan-1.0.0-hadoop1/bin:/root/presto-server-0.137/bin:/root/airflow/bin:/root/flink-1.0.0/bin:/root/zeppelin-0.6.0/bin:/root/sbt/bin:/root/nifi-0.6.1/bin:/root/webdis:/root/redis-3.0.5/bin:/root/apache-hive-1.2.1-bin/bin:/root/hadoop-2.6.0/bin:/root/kibana-4.5.0-linux-x64/bin:/root/logstash-2.3.0/bin:/root/elasticsearch-2.3.0/bin:/root/confluent-3.0.0/bin:/root/confluent-3.0.0/bin:/root/spark-1.6.1-bin-fluxcapacitor/tachyon/bin:/root/spark-1.6.1-bin-fluxcapacitor/bin:/root/spark-1.6.1-bin-fluxcapacitor/sbin:/root/apache-cassandra-2.2.6/bin:/root/pipeline/bin/cli:/root/pipeline/bin/cluster:/root/pipeline/bin/docker:/root/pipeline/bin/initial:/root/pipeline/bin/kafka:/root/pipeline/bin/rest:/root/pipeline/bin/service:/root/pipeline/bin/util:/root/bazel-0.3.0/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
export PIPELINE_HOME='/root/pipeline'
export PMML_EVALUATOR_VERSION='1.2.14'
export PMML_MODEL_METRO_VERSION='1.2.15'
export PMML_MODEL_VERSION='1.2.15'
export PRESTO_HOME='/root/presto-server-0.137'
export PRESTO_VERSION='0.137'
export PWD='/root/pipeline/myapps/jupyter/Spark/PMML'
export PYSPARK_SUBMIT_ARGS='--master spark://127.0.0.1:7077 --jars /root/pipeline/myapps/pmml/spark/1.6.1/lib/jpmml-sparkml-package-1.0-SNAPSHOT.jar,/root/pipeline/myapps/spark/redis/lib/spark-redis_2.10-0.2.0.jar,/usr/share/java/mysql-connector-java.jar,/root/pipeline/myapps/spark/ml/lib/spark-corenlp_2.10-0.1.jar,/root/pipeline/myapps/spark/ml/lib/stanford-corenlp-3.6.0-models.jar,/root/pipeline/myapps/spark/ml/target/scala-2.10/ml_2.10-1.0.jar,/root/pipeline/myapps/spark/sql/target/scala-2.10/sql_2.10-1.0.jar,/root/pipeline/myapps/spark/core/target/scala-2.10/core_2.10-1.0.jar,/root/pipeline/myapps/spark/streaming/target/scala-2.10/streaming_2.10-1.0.jar,/root/pipeline/myapps/serving/spark/target/scala-2.10/spark-serving_2.10-1.0.jar --repositories http://dl.bintray.com/spark-packages/maven,https://oss.sonatype.org/content/repositories/snapshots,https://repository.apache.org/content/groups/snapshots --packages tjhunter:tensorframes:0.2.2-s_2.10,com.maxmind.geoip2:geoip2:2.5.0,com.netflix.dyno:dyno-jedis:1.4.6,org.json4s:json4s-jackson_2.10:3.3.0,amplab:spark-indexedrdd:0.3,org.apache.spark:spark-streaming-kafka-assembly_2.10:1.6.1,org.elasticsearch:elasticsearch-spark_2.10:2.3.0.BUILD-SNAPSHOT,com.datastax.spark:spark-cassandra-connector_2.10:1.4.0,redis.clients:jedis:2.7.3,com.twitter:algebird-core_2.10:0.11.0,com.databricks:spark-avro_2.10:2.0.1,com.databricks:spark-csv_2.10:1.5.0,org.apache.nifi:nifi-spark-receiver:0.6.1,com.madhukaraphatak:java-sizeof_2.10:0.1,com.databricks:spark-xml_2.10:0.3.1,edu.stanford.nlp:stanford-corenlp:3.6.0,org.jblas:jblas:1.2.4,graphframes:graphframes:0.1.0-spark1.6,com.amazonaws:aws-java-sdk:1.11.39 pyspark-shell'
export PYTHONPATH='/root/pipeline/myapps/pmml/spark/1.6.1/lib/jpmml_sparkml-1.0rc0-py2.7.egg'
export REDIS_HOME='/root/redis-3.0.5'
export REDIS_VERSION='3.0.5'
export SBT_ASSEMBLY_PLUGIN_VERSION='0.14.0'
export SBT_HOME='/root/sbt'
export SBT_OPTS='-Xmx10G -XX:+CMSClassUnloadingEnabled'
export SBT_SPARK_PACKAGES_PLUGIN_VERSION='0.2.3'
export SBT_VERSION='0.13.9'
export SCALATEST_VERSION='2.2.4'
export SCALA_MAJOR_VERSION='2.10'
export SCALA_VERSION='2.10.5'
export SCRIPTS_HOME='/root/pipeline/bin'
export SHLVL='2'
export SPARK_AVRO_CONNECTOR_VERSION='2.0.1'
export SPARK_CASSANDRA_CONNECTOR_VERSION='1.4.0'
export SPARK_CSV_CONNECTOR_VERSION='1.5.0'
export SPARK_ELASTICSEARCH_CONNECTOR_VERSION='2.3.0.BUILD-SNAPSHOT'
export SPARK_EXAMPLES_JAR='/root/spark-1.6.1-bin-fluxcapacitor/lib/spark-examples-1.6.1-hadoop2.6.0.jar'
export SPARK_HOME='/root/spark-1.6.1-bin-fluxcapacitor'
export SPARK_MASTER='spark://127.0.0.1:7077'
export SPARK_NIFI_CONNECTOR_VERSION='0.6.1'
export SPARK_OTHER_VERSION='2.0.1-SNAPSHOT'
export SPARK_REDIS_CONNECTOR_VERSION='0.2.0'
export SPARK_REPOSITORIES='http://dl.bintray.com/spark-packages/maven,https://oss.sonatype.org/content/repositories/snapshots,https://repository.apache.org/content/groups/snapshots'
export SPARK_SUBMIT_ARGS='--jars /root/pipeline/myapps/pmml/spark/1.6.1/lib/jpmml-sparkml-package-1.0-SNAPSHOT.jar,/root/pipeline/myapps/spark/redis/lib/spark-redis_2.10-0.2.0.jar,/usr/share/java/mysql-connector-java.jar,/root/pipeline/myapps/spark/ml/lib/spark-corenlp_2.10-0.1.jar,/root/pipeline/myapps/spark/ml/lib/stanford-corenlp-3.6.0-models.jar,/root/pipeline/myapps/spark/ml/target/scala-2.10/ml_2.10-1.0.jar,/root/pipeline/myapps/spark/sql/target/scala-2.10/sql_2.10-1.0.jar,/root/pipeline/myapps/spark/core/target/scala-2.10/core_2.10-1.0.jar,/root/pipeline/myapps/spark/streaming/target/scala-2.10/streaming_2.10-1.0.jar,/root/pipeline/myapps/serving/spark/target/scala-2.10/spark-serving_2.10-1.0.jar --repositories http://dl.bintray.com/spark-packages/maven,https://oss.sonatype.org/content/repositories/snapshots,https://repository.apache.org/content/groups/snapshots --packages tjhunter:tensorframes:0.2.2-s_2.10,com.maxmind.geoip2:geoip2:2.5.0,com.netflix.dyno:dyno-jedis:1.4.6,org.json4s:json4s-jackson_2.10:3.3.0,amplab:spark-indexedrdd:0.3,org.apache.spark:spark-streaming-kafka-assembly_2.10:1.6.1,org.elasticsearch:elasticsearch-spark_2.10:2.3.0.BUILD-SNAPSHOT,com.datastax.spark:spark-cassandra-connector_2.10:1.4.0,redis.clients:jedis:2.7.3,com.twitter:algebird-core_2.10:0.11.0,com.databricks:spark-avro_2.10:2.0.1,com.databricks:spark-csv_2.10:1.5.0,org.apache.nifi:nifi-spark-receiver:0.6.1,com.madhukaraphatak:java-sizeof_2.10:0.1,com.databricks:spark-xml_2.10:0.3.1,edu.stanford.nlp:stanford-corenlp:3.6.0,org.jblas:jblas:1.2.4,graphframes:graphframes:0.1.0-spark1.6,com.amazonaws:aws-java-sdk:1.11.39'
export SPARK_SUBMIT_JARS='/root/pipeline/myapps/pmml/spark/1.6.1/lib/jpmml-sparkml-package-1.0-SNAPSHOT.jar,/root/pipeline/myapps/spark/redis/lib/spark-redis_2.10-0.2.0.jar,/usr/share/java/mysql-connector-java.jar,/root/pipeline/myapps/spark/ml/lib/spark-corenlp_2.10-0.1.jar,/root/pipeline/myapps/spark/ml/lib/stanford-corenlp-3.6.0-models.jar,/root/pipeline/myapps/spark/ml/target/scala-2.10/ml_2.10-1.0.jar,/root/pipeline/myapps/spark/sql/target/scala-2.10/sql_2.10-1.0.jar,/root/pipeline/myapps/spark/core/target/scala-2.10/core_2.10-1.0.jar,/root/pipeline/myapps/spark/streaming/target/scala-2.10/streaming_2.10-1.0.jar,/root/pipeline/myapps/serving/spark/target/scala-2.10/spark-serving_2.10-1.0.jar'
export SPARK_SUBMIT_PACKAGES='tjhunter:tensorframes:0.2.2-s_2.10,com.maxmind.geoip2:geoip2:2.5.0,com.netflix.dyno:dyno-jedis:1.4.6,org.json4s:json4s-jackson_2.10:3.3.0,amplab:spark-indexedrdd:0.3,org.apache.spark:spark-streaming-kafka-assembly_2.10:1.6.1,org.elasticsearch:elasticsearch-spark_2.10:2.3.0.BUILD-SNAPSHOT,com.datastax.spark:spark-cassandra-connector_2.10:1.4.0,redis.clients:jedis:2.7.3,com.twitter:algebird-core_2.10:0.11.0,com.databricks:spark-avro_2.10:2.0.1,com.databricks:spark-csv_2.10:1.5.0,org.apache.nifi:nifi-spark-receiver:0.6.1,com.madhukaraphatak:java-sizeof_2.10:0.1,com.databricks:spark-xml_2.10:0.3.1,edu.stanford.nlp:stanford-corenlp:3.6.0,org.jblas:jblas:1.2.4,graphframes:graphframes:0.1.0-spark1.6,com.amazonaws:aws-java-sdk:1.11.39'
export SPARK_SUBMIT_PYFILES='/root/pipeline/myapps/pmml/spark/1.6.1/lib/jpmml.py'
export SPARK_VERSION='1.6.1'
export SPARK_XML_VERSION='0.3.1'
export SPRING_BOOT_VERSION='1.3.5.RELEASE'
export SPRING_CLOUD_VERSION='1.1.2.RELEASE'
export SPRING_CORE_VERSION='4.3.0.RELEASE'
export SPRING_PROFILES_ACTIVE='local'
export STANFORD_CORENLP_VERSION='3.6.0'
export TACHYON_HOME='/root/spark-1.6.1-bin-fluxcapacitor/tachyon'
export TENSORFLOW_HOME='/root/tensorflow'
export TENSORFLOW_SERVING_HOME='/root/serving'
export TENSORFLOW_SERVING_VERSION='0.4.1'
export TENSORFLOW_VERSION='0.10.0'
export TENSORFRAMES_VERSION='0.2.2'
export TERM='xterm-color'
export TITAN_HOME='/root/titan-1.0.0-hadoop1'
export TITAN_VERSION='1.0.0-hadoop1'
export WEBDIS_HOME='/root/webdis'
export WORK_HOME='/root/pipeline/work'
export ZEPPELIN_HOME='/root/zeppelin-0.6.0'
export ZEPPELIN_VERSION='0.6.0'
export ZOOKEEPER_HOME='/root/confluent-3.0.0'
export _='/usr/bin/nohup'

## Load Dataset into Spark Cluster

In [4]:
data = sqlContext.read.format("csv").option("inferSchema", "true").option("header", "true").load("/root/pipeline/datasets/R/census.csv")

data.collect()

[Row(age=39, workclass=u'State-gov', education=u'Bachelors', education_num=13, marital_status=u'Never-married', occupation=u'Adm-clerical', relationship=u'Not-in-family', race=u'White', sex=u'Male', capital_gain=2174, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=50, workclass=u'Self-emp-not-inc', education=u'Bachelors', education_num=13, marital_status=u'Married-civ-spouse', occupation=u'Exec-managerial', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=13, native_country=u'United-States', income=u'<=50K'),
 Row(age=38, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Divorced', occupation=u'Handlers-cleaners', relationship=u'Not-in-family', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=53, workclass=u'Private', education=u'11th', education_num=7, marital_status=u'Married-civ-spouse', occupation=u'Handlers-cleaners', relationship=u'Husband', race=u'Black', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=28, workclass=u'Private', education=u'Bachelors', education_num=13, marital_status=u'Married-civ-spouse', occupation=u'Prof-specialty', relationship=u'Wife', race=u'Black', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'Cuba', income=u'<=50K'),
 Row(age=37, workclass=u'Private', education=u'Masters', education_num=14, marital_status=u'Married-civ-spouse', occupation=u'Exec-managerial', relationship=u'Wife', race=u'White', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=49, workclass=u'Private', education=u'9th', education_num=5, marital_status=u'Married-spouse-absent', occupation=u'Other-service', relationship=u'Not-in-family', race=u'Black', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=16, native_country=u'Jamaica', income=u'<=50K'),
 Row(age=52, workclass=u'Self-emp-not-inc', education=u'HS-grad', education_num=9, marital_status=u'Married-civ-spouse', occupation=u'Exec-managerial', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=45, native_country=u'United-States', income=u'>50K'),
 Row(age=31, workclass=u'Private', education=u'Masters', education_num=14, marital_status=u'Never-married', occupation=u'Prof-specialty', relationship=u'Not-in-family', race=u'White', sex=u'Female', capital_gain=14084, capital_loss=0, hours_per_week=50, native_country=u'United-States', income=u'>50K'),
 Row(age=42, workclass=u'Private', education=u'Bachelors', education_num=13, marital_status=u'Married-civ-spouse', occupation=u'Exec-managerial', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=5178, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'>50K'),
 Row(age=37, workclass=u'Private', education=u'Some-college', education_num=10, marital_status=u'Married-civ-spouse', occupation=u'Exec-managerial', relationship=u'Husband', race=u'Black', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=80, native_country=u'United-States', income=u'>50K'),
 Row(age=30, workclass=u'State-gov', education=u'Bachelors', education_num=13, marital_status=u'Married-civ-spouse', occupation=u'Prof-specialty', relationship=u'Husband', race=u'Asian-Pac-Islander', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'India', income=u'>50K'),
 Row(age=23, workclass=u'Private', education=u'Bachelors', education_num=13, marital_status=u'Never-married', occupation=u'Adm-clerical', relationship=u'Own-child', race=u'White', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=30, native_country=u'United-States', income=u'<=50K'),
 Row(age=32, workclass=u'Private', education=u'Assoc-acdm', education_num=12, marital_status=u'Never-married', occupation=u'Sales', relationship=u'Not-in-family', race=u'Black', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=50, native_country=u'United-States', income=u'<=50K'),
 Row(age=34, workclass=u'Private', education=u'7th-8th', education_num=4, marital_status=u'Married-civ-spouse', occupation=u'Transport-moving', relationship=u'Husband', race=u'Amer-Indian-Eskimo', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=45, native_country=u'Mexico', income=u'<=50K'),
 Row(age=25, workclass=u'Self-emp-not-inc', education=u'HS-grad', education_num=9, marital_status=u'Never-married', occupation=u'Farming-fishing', relationship=u'Own-child', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=35, native_country=u'United-States', income=u'<=50K'),
 Row(age=32, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Never-married', occupation=u'Machine-op-inspct', relationship=u'Unmarried', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=38, workclass=u'Private', education=u'11th', education_num=7, marital_status=u'Married-civ-spouse', occupation=u'Sales', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=50, native_country=u'United-States', income=u'<=50K'),
 Row(age=43, workclass=u'Self-emp-not-inc', education=u'Masters', education_num=14, marital_status=u'Divorced', occupation=u'Exec-managerial', relationship=u'Unmarried', race=u'White', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=45, native_country=u'United-States', income=u'>50K'),
 Row(age=40, workclass=u'Private', education=u'Doctorate', education_num=16, marital_status=u'Married-civ-spouse', occupation=u'Prof-specialty', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=60, native_country=u'United-States', income=u'>50K'),
 Row(age=54, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Separated', occupation=u'Other-service', relationship=u'Unmarried', race=u'Black', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=20, native_country=u'United-States', income=u'<=50K'),
 Row(age=35, workclass=u'Federal-gov', education=u'9th', education_num=5, marital_status=u'Married-civ-spouse', occupation=u'Farming-fishing', relationship=u'Husband', race=u'Black', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=43, workclass=u'Private', education=u'11th', education_num=7, marital_status=u'Married-civ-spouse', occupation=u'Transport-moving', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=2042, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=59, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Divorced', occupation=u'Tech-support', relationship=u'Unmarried', race=u'White', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=56, workclass=u'Local-gov', education=u'Bachelors', education_num=13, marital_status=u'Married-civ-spouse', occupation=u'Tech-support', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'>50K'),
 Row(age=19, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Never-married', occupation=u'Craft-repair', relationship=u'Own-child', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=39, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Divorced', occupation=u'Exec-managerial', relationship=u'Not-in-family', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=80, native_country=u'United-States', income=u'<=50K'),
 Row(age=49, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Married-civ-spouse', occupation=u'Craft-repair', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=23, workclass=u'Local-gov', education=u'Assoc-acdm', education_num=12, marital_status=u'Never-married', occupation=u'Protective-serv', relationship=u'Not-in-family', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=52, native_country=u'United-States', income=u'<=50K'),
 Row(age=20, workclass=u'Private', education=u'Some-college', education_num=10, marital_status=u'Never-married', occupation=u'Sales', relationship=u'Own-child', race=u'Black', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=44, native_country=u'United-States', income=u'<=50K'),
 Row(age=45, workclass=u'Private', education=u'Bachelors', education_num=13, marital_status=u'Divorced', occupation=u'Exec-managerial', relationship=u'Own-child', race=u'White', sex=u'Male', capital_gain=0, capital_loss=1408, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=30, workclass=u'Federal-gov', education=u'Some-college', education_num=10, marital_status=u'Married-civ-spouse', occupation=u'Adm-clerical', relationship=u'Own-child', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=22, workclass=u'State-gov', education=u'Some-college', education_num=10, marital_status=u'Married-civ-spouse', occupation=u'Other-service', relationship=u'Husband', race=u'Black', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=15, native_country=u'United-States', income=u'<=50K'),
 Row(age=48, workclass=u'Private', education=u'11th', education_num=7, marital_status=u'Never-married', occupation=u'Machine-op-inspct', relationship=u'Unmarried', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'Puerto-Rico', income=u'<=50K'),
 Row(age=21, workclass=u'Private', education=u'Some-college', education_num=10, marital_status=u'Never-married', occupation=u'Machine-op-inspct', relationship=u'Own-child', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=19, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Married-AF-spouse', occupation=u'Adm-clerical', relationship=u'Wife', race=u'White', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=25, native_country=u'United-States', income=u'<=50K'),
 Row(age=48, workclass=u'Self-emp-not-inc', education=u'Assoc-acdm', education_num=12, marital_status=u'Married-civ-spouse', occupation=u'Prof-specialty', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=31, workclass=u'Private', education=u'9th', education_num=5, marital_status=u'Married-civ-spouse', occupation=u'Machine-op-inspct', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=43, native_country=u'United-States', income=u'<=50K'),
 Row(age=53, workclass=u'Self-emp-not-inc', education=u'Bachelors', education_num=13, marital_status=u'Married-civ-spouse', occupation=u'Prof-specialty', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=24, workclass=u'Private', education=u'Bachelors', education_num=13, marital_status=u'Married-civ-spouse', occupation=u'Tech-support', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=50, native_country=u'United-States', income=u'<=50K'),
 Row(age=49, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Separated', occupation=u'Adm-clerical', relationship=u'Unmarried', race=u'White', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=25, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Never-married', occupation=u'Handlers-cleaners', relationship=u'Not-in-family', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=35, native_country=u'United-States', income=u'<=50K'),
 Row(age=57, workclass=u'Federal-gov', education=u'Bachelors', education_num=13, marital_status=u'Married-civ-spouse', occupation=u'Prof-specialty', relationship=u'Husband', race=u'Black', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'>50K'),
 Row(age=53, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Married-civ-spouse', occupation=u'Machine-op-inspct', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=38, native_country=u'United-States', income=u'<=50K'),
 Row(age=44, workclass=u'Private', education=u'Masters', education_num=14, marital_status=u'Divorced', occupation=u'Exec-managerial', relationship=u'Unmarried', race=u'White', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=41, workclass=u'State-gov', education=u'Assoc-voc', education_num=11, marital_status=u'Married-civ-spouse', occupation=u'Craft-repair', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=29, workclass=u'Private', education=u'Assoc-voc', education_num=11, marital_status=u'Never-married', occupation=u'Prof-specialty', relationship=u'Not-in-family', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=43, native_country=u'United-States', income=u'<=50K'),
 Row(age=25, workclass=u'Private', education=u'Some-college', education_num=10, marital_status=u'Married-civ-spouse', occupation=u'Exec-managerial', relationship=u'Wife', race=u'Other', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=47, workclass=u'Private', education=u'Prof-school', education_num=15, marital_status=u'Married-civ-spouse', occupation=u'Prof-specialty', relationship=u'Wife', race=u'White', sex=u'Female', capital_gain=0, capital_loss=1902, hours_per_week=60, native_country=u'Honduras', income=u'>50K'),
 Row(age=50, workclass=u'Federal-gov', education=u'Bachelors', education_num=13, marital_status=u'Divorced', occupation=u'Exec-managerial', relationship=u'Not-in-family', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=55, native_country=u'United-States', income=u'>50K'),
 Row(age=47, workclass=u'Self-emp-inc', education=u'HS-grad', education_num=9, marital_status=u'Divorced', occupation=u'Exec-managerial', relationship=u'Not-in-family', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=60, native_country=u'United-States', income=u'<=50K'),
 Row(age=43, workclass=u'Private', education=u'Some-college', education_num=10, marital_status=u'Married-civ-spouse', occupation=u'Tech-support', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'>50K'),
 Row(age=46, workclass=u'Private', education=u'5th-6th', education_num=3, marital_status=u'Married-civ-spouse', occupation=u'Machine-op-inspct', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'Mexico', income=u'<=50K'),
 Row(age=35, workclass=u'Private', education=u'Assoc-voc', education_num=11, marital_status=u'Married-civ-spouse', occupation=u'Other-service', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'Puerto-Rico', income=u'<=50K'),
 Row(age=41, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Married-civ-spouse', occupation=u'Adm-clerical', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=48, native_country=u'United-States', income=u'<=50K'),
 Row(age=30, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Married-civ-spouse', occupation=u'Machine-op-inspct', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=5013, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=30, workclass=u'Private', education=u'Bachelors', education_num=13, marital_status=u'Married-civ-spouse', occupation=u'Sales', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=2407, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=48, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Married-civ-spouse', occupation=u'Transport-moving', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=42, workclass=u'Private', education=u'Doctorate', education_num=16, marital_status=u'Married-civ-spouse', occupation=u'Prof-specialty', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=45, native_country=u'United-States', income=u'>50K'),
 Row(age=29, workclass=u'Private', education=u'Some-college', education_num=10, marital_status=u'Divorced', occupation=u'Tech-support', relationship=u'Not-in-family', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=58, native_country=u'United-States', income=u'<=50K'),
 Row(age=36, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Married-civ-spouse', occupation=u'Craft-repair', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=28, workclass=u'Private', education=u'Some-college', education_num=10, marital_status=u'Divorced', occupation=u'Adm-clerical', relationship=u'Not-in-family', race=u'White', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),
 Row(age=53, workclass=u'Private', education=u'HS-grad', education_num=9, marital_status=u'Married-civ-spouse', occupation=u'Adm-clerical', relationship=u'Wife', race=u'White', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'>50K'),
 Row(age=49, workclass=u'Self-emp-inc', education=u'Some-college', education_num=10, marital_status=u'Married-civ-spouse', occupation=u'Exec-managerial', relationship=u'Husband', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=50, native_country=u'United-States', income=u'>50K'),
 Row(age=19, workclass=u'Private', education=u'Some-college', education_num=10, marital_status=u'Never-married', occupation=u'Prof-specialty', relationship=u'Own-child', race=u'White', sex=u'Male', capital_gain=0, capital_loss=0, hours_per_week=32, native_country=u'United-States', income=u'<=50K'),
 Row(age=31, workclass=u'Private', education=u'Bachelors', education_num=13, marital_status=u'Separated', occupation=u'Sales', relationship=u'Own-child', race=u'Black', sex=u'Female', capital_gain=0, capital_loss=0, hours_per_week=40, native_country=u'United-States', income=u'<=50K'),

## Build Decision Tree (Regression) with Spark ML Pipeline

In [5]:
from pyspark.ml import Pipeline
from pyspark.ml.feature import RFormula
from pyspark.ml.classification import DecisionTreeClassifier


formula = RFormula(formula = "income ~ .")
classifier = DecisionTreeClassifier()
pipeline = Pipeline(stages = [formula, classifier])
pipelineModel = pipeline.fit(data)

pipelineModel

PipelineModel_40b7ad7b7d7a6e6901a5

## Convert Spark ML Model and Pipeline to PMML

In [6]:
from jpmml_sparkml import toPMMLBytes

pmmlBytes = toPMMLBytes(sparkContext, data, pipelineModel)

str(pmmlBytes)

RuntimeError: JPMML-SparkML not found on classpath